name: cicd-test

on:
  push:
    branches:
      - main

jobs:
  build_and_push_docker:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.x

      - name: Display Current Directory
        run: ls

      - name: Change to project directory and build
        run: |
          cd HamroCommunity
          dotnet publish -c Release -o ./app
          docker build -t hamrocommunity .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker Image
        run: docker tag hamrocommunity ${{ secrets.DOCKER_USERNAME }}/hamrocommunity:latest
        
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/hamrocommunity:latest
        
      - name: Pull Docker Image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/hamrocommunity:latest

      - name: Run Docker Image
        run: docker run --name hamrocommunity-container -d -p 8089:80 ${{ secrets.DOCKER_USERNAME }}/hamrocommunity:latest

      - name: Show Running Container
        run: docker ps
